### ISSUE TITLE
Rename arbitrum to arbitrum-one and add flavours

### ISSUE THREAD

**Issue by chriswessels** [graphops/launchpad-namespaces#74]
As per https://docs.arbitrum.io/for-devs/concepts/public-chains, Arbitrum One has a `mainnet` deployment and a `goerli` deployment.

- [x] Rename `arbitrum` namespace to `arbitrum-one`
- [x] Add `mainnet` flavour
- [x] Add `goerli` flavour
